### ISSUE TITLE
training script

### ISSUE THREAD

**Issue by hondaathma** [una-dinosauria/human-motion-prediction#19]
Hi,
Is there any plans to release the training script?

**Comment by una-dinosauria** [comment]
Please have a look at the [README](https://github.com/una-dinosauria/human-motion-prediction/blob/master/README.md). The demo

`python src/translate.py --action walking --seq_length_out 25 --iterations 10000`

and all the commands below https://github.com/una-dinosauria/human-motion-prediction#rnn-models are training networks from scratch.
