### ISSUE TITLE
needs .txt files but human 3.6m has .cdf files

### ISSUE THREAD

**Issue by rajeev595** [una-dinosauria/human-motion-prediction#24]
Hi Julieta,

Thanks for the code to your paper.

I was trying to run your code for pre-processing the data. Specifically, I face the issue in the following lines of code in the load_data function (in data_utils.py)

`        filename = '{0}/S{1}/{2}_{3}.txt'.format( path_to_dataset, subj, action, subact)
        action_sequence = readCSVasFloat(filename)`

Can you please explain how you converted .cdf files to .txt files for the above usage ?

Thanks.

**Comment by una-dinosauria** [comment]
Hi @rajeev595,

Our code takes as input the .txt files that Ashesh Jain @ Stanford generated: http://www.cs.stanford.edu/people/ashesh/h3.6m.zip

We did not modify their data, and we do not have access to their preprocessing code, so it's probably best to contact them with this question.

Cheers,

**Comment by rajeev595** [comment]
Thanks, Julieta for the prompt response.
