### ISSUE TITLE
How to get the Prediction results? 

### ISSUE THREAD

**Issue by Ammola** [una-dinosauria/human-motion-prediction#33]
Sorry @una-dinosauria this is a very basic question but I need to ask it.
Could you tell me please where to find the prediction results in your code? 

I want to try your code with another dataset but I don't know how to get the prediction results.

Thanks

**Comment by una-dinosauria** [comment]
Sorry, looking back my code is pretty messy and not super modular :(

To obtain a prediction, go here:
https://github.com/una-dinosauria/human-motion-prediction/blob/c9a2774fe59bb78c6ec6d04e15f2cb7243c4348c/src/translate.py#L191-L194
