### ISSUE TITLE
Understanding the structure of H3.6M dataset

### ISSUE THREAD

**Issue by KavinduZoysa** [una-dinosauria/human-motion-prediction#36]
Hi Una-dinosauria,

First of all, I need to thank you for making this fantastic paper and code available publicly and it is really helpful for my academics. 

I have a very basic question. Can you please explain the structure of the dataset and what is the meaning of 99 numbers in each row? In the [site](http://vision.imar.ro/human3.6m/description.php), they are describing 96 data, but in H3.6M dataset there are 99 data in each raw.

**Comment by una-dinosauria** [comment]
IIRC, the first three numbers are the global translation. The rest are (99-3)/3 = 32 articulations that define the joint angles of the human body. 

You may want to look at https://github.com/una-dinosauria/human-motion-prediction/issues/21#issuecomment-348038807 to get see how you can visualize the data. Following the visualization code should make it clear what the data means.

Cheers,

**Comment by una-dinosauria** [comment]
Hi!

No, sorry I can't do that. You can use our code to visualize and perhaps some more code to measure standard deviations so you can find out.

Cheers,

**Comment by KavinduZoysa** [comment]
Thank you for the support.
