### ISSUE TITLE
Reason to use 54 dimensions

### ISSUE THREAD

**Issue by KavinduZoysa** [una-dinosauria/human-motion-prediction#37]
Hi Una-dinosauria,

Can you please explain me the reason to use only 54 dimensions out of 99 dimensions. I tried to find it in the paper and the code. But I was unable to find. Your response is highly appreciated.

Thank you,
Kavindu

**Comment by una-dinosauria** [comment]
Hi,

Could you please tell me in what part of the code do you see the 54 dimensions?

In general, not all dimensions vary. If they don't then there is no need to model them.
Some other dimensions vary very little (eg < 1e-4). In that case, the normalization process, which subtracts the mean and divides by the standard deviation migth run into numerical issues. Therefore we sometimes also ignore dimensions with very small stdevs.

**Comment by KavinduZoysa** [comment]
Hi Una-dinosauria,

I have a conflict in two places.

1.   **self.HUMAN_SIZE = 54** in the [seq2seq_model.py](https://github.com/una-dinosauria/human-motion-prediction/blob/c9a2774fe59bb78c6ec6d04e15f2cb7243c4348c/src/seq2seq_model.py#L63) file
2.   **dimensions_to_use.extend( list(np.where(data_std >= 1e-4)[0])** ) in [data_utils.py](https://github.com/una-dinosauria/human-motion-prediction/blob/c9a2774fe59bb78c6ec6d04e15f2cb7243c4348c/src/data_utils.py#L322) file

In the first one, 54 is defined and the second one the size of dimensions_to_use is 54. Therefore my question of is the 54 defined in first one according to the size of the array dimensions_to_use?

Thank you,
Kavindu

**Comment by una-dinosauria** [comment]
I think that is the case.

**Comment by KavinduZoysa** [comment]
Thank you for the confirmation.
