### ISSUE TITLE
A question about sampling_based loss

### ISSUE THREAD

**Issue by KavinduZoysa** [una-dinosauria/human-motion-prediction#41]
Hi @una-dinosauria 

I have a question about sampling_based loss. 

According to my understanding, the sampling_based loss means giving the previous output to the current input inside the decoder. Also, I think it is done inside the seq2seq_model.py file and the corresponding line is mentioned below(**loop function**).
https://github.com/una-dinosauria/human-motion-prediction/blob/c9a2774fe59bb78c6ec6d04e15f2cb7243c4348c/src/seq2seq_model.py#L124

Could you please tell me that my understanding is correct or wrong?
If I am wrong can you please explain me how the sampling_based loss is calculated in the code.

Your response is highly appreciated.

Thank you,
Kavindu

**Comment by una-dinosauria** [comment]
That is correct.

**Comment by KavinduZoysa** [comment]
Hi @una-dinosauria,

Thanks a lot for your information. I have one more question. Why we use the word "**loss**"(sampling_based loss) here? (According to my understanding we are not doing any loss calculation here)

Thank you,
Kavindu

**Comment by una-dinosauria** [comment]
Oh this just means that, while training, we minimize the loss that is the difference between the ground truth and what our network predicts during _k_ timesteps (as opposed to the usual training, where you minimize the difference between ground truth and what your network predicts at each timestep, after being fed the ground truth).

**Comment by KavinduZoysa** [comment]
Hi @una-dinosauria,

Thank you for the information. But still, I am confusing because simply sampling_based loss means adding the previous prediction to the current input. Here we do not consider the ground truth when we are getting the  sampling_based loss. Can you please help me to clear this problem.

According to the code, I cannot see that we are getting the difference between the ground truth and what network predicts during k timesteps under sampling_based loss. 

Thank you,
Kavindu

**Comment by una-dinosauria** [comment]
> Here we do not consider the ground truth when we are getting the sampling_based loss. Can you please help me to clear this problem.

We do. The prediction is on the upper right, and the loss is computed between that and the ground truth (not shown in the diagram).

> According to the code, I cannot see that we are getting the difference between the ground truth and what network predicts during k timesteps under sampling_based loss.

The loss is right here: https://github.com/una-dinosauria/human-motion-prediction/blob/c9a2774fe59bb78c6ec6d04e15f2cb7243c4348c/src/seq2seq_model.py#L145

`dec_out` is the ground truth.

> I think the sampling_based loss is indicated by the blue broken line in the below figure.

Yes, as opposed to always giving the ground truth as input to the decoder.

**Comment by KavinduZoysa** [comment]
Thanks a lot for the explanation.
