### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by enriccorona** [una-dinosauria/human-motion-prediction#51]
Hi!

I implemented a pytorch version of the code in [this fork](https://github.com/enriccorona/human-motion-prediction-pytorch). The results are similar for the demos I tried so far.

**Comment by SuperShinyEyes** [comment]
I tested the code and the following worked.
```python
python src/translate.py --action walking --seq_length_out 25 --iterations 10000
python src/translate.py --action walking --seq_length_out 25 --iterations 10000 --sample --load 10000
python src/forward_kinematics.py
```
Thank you Enrico!

**Comment by una-dinosauria** [comment]
Thank you. Adding note to README.

**Comment by chcchc97** [comment]
Hello~ Which pytorch version can work?@Enrico
