### ISSUE TITLE
Camera intrinsics and Extrsinics to convert to image coordinates

### ISSUE THREAD

**Issue by alecda573** [una-dinosauria/human-motion-prediction#65]
I have downloaded the euler angle format of h3.6m and have applied forward kinematics to get the joint locations in the cameras reference frame. Is there any code to convert to image coordinates or can you supply the camera intrinsics/extrinsics to perform this conversion?

**Comment by una-dinosauria** [comment]
Hi @alecda573,

The camera parameters are given on the H3.6M website, on a file called `metadata.xml`.

You can use 

https://github.com/una-dinosauria/3d-pose-baseline/blob/666080d86a96666d499300719053cc8af7ef51c8/src/cameras.py#L151-L174

to parse the parameters.

**Comment by alecda573** [comment]
@una-dinosauria Thanks for the response! Just to make sure I am correct after applying forward kinematics the cartesian coordinate representation is in camerate coordinate system right? 

Would you project_to_camera function in data_utils work to get to image coordinates?

**Comment by alecda573** [comment]
@una-dinosauria or would it be possible to share the 3d joint locations and corresponding 2d in image coordinates as nobody is maintaining the h3.6m dataset anymore, they are not activating registration requests.
