### ISSUE TITLE
Sampling rate of the data

### ISSUE THREAD

**Issue by pvmilk** [una-dinosauria/human-motion-prediction#8]
I would like to know what is the **actual** sampling rate of the data?

I think you had pointed this out to the author of Structure-RNN in the following thread that it is 25fps, but it is not very clear to me.
https://github.com/asheshjain399/RNNexp/issues/6

I check your source code in 
- [src/data_utils.py#L215](https://github.com/una-dinosauria/human-motion-prediction/blob/master/src/data_utils.py#L215)  : Down-sampling by two (200 fps --> 100 fps)
- [src/seq2seq_model.py#438](https://github.com/una-dinosauria/human-motion-prediction/blob/master/src/seq2seq_model.py#438) : Select 8 data from the original sequence (100 fps --> 100 fps)

If the original data is 200fps, I think the sampling rate of your data should be 100 fps, not 25 fps as mentioned in [src/translate.py#L34](https://github.com/una-dinosauria/human-motion-prediction/blob/master/src/translate.py#L34). 

Thank you.

**Comment by pvmilk** [comment]
Thank you for clarification.
I couldn't verify the original H3.6M dataset myself, due to their data format.

**Comment by una-dinosauria** [comment]
> I couldn't verify the original H3.6M dataset myself, due to their data format.

Right, they used a strange format that matlab can read out of the box, but is tricky to read from python directly. I'm closing this issue now.
