### ISSUE TITLE
Small bug in the code

### ISSUE THREAD

**Issue by Seleucia** [una-dinosauria/human-motion-prediction#9]
Hello, 
Thank you very much for code of your paper (paper was quite good also). I think there is a small bug in your code. while computing error you are checking the estimated value std, and selecting the dimensions to use. I think this is not the right way selecting dimensions( When your model estimate quite low number you can still get good results). Also referenced [code](https://github.com/asheshjain399/RNNexp/blob/srnn/structural_rnn/CRFProblems/H3.6m/dataParser/Utils/motionGenerationError.m#L40-L54) finding dimensions to use as I said.

[Bug line](https://github.com/una-dinosauria/human-motion-prediction/blob/master/src/translate.py#L225)

PS: I fixed the code, and tried to run model, it seems it is still converging quite good :)
Have a nice time in Havai

**Comment by una-dinosauria** [comment]
Oh I see. So are you saying that in

```python
idx_to_use = np.where( np.std( eulerchannels_pred, 0 ) > 1e-4 )[0]
```

`eulerchannels_pred` could have a small number of samples? Yes, that might be a problem :S

Thank you so much for reporting this. Would you mind submitting your fix as a pull request?
